Metrics/LineLength:
  Max: 200

  Exclude:
    - 'features/**/**.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Lint/RescueException:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

