version: 2
jobs:
  rubocop:
    parameters:
      ruby:
        type: string
    docker:
      - image: circleci/ruby:<<parameters.ruby>>
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rubocop

  build:
    machine: true
    working_directory: ~/repo
    steps:
      - run:
          name: Rubocop
          command: bundle exec rubocop
      - checkout
      - run: docker-compose build
      - run: docker-compose run bbt

  
      

workflows:
  version: 2
  ui_testing:
    jobs:
      - rubocop
      - build

